# Lychee link checker configuration
# https://lychee.cli.rs/

# Exclude patterns
exclude = ["^mailto:", "^https://localhost", "^http://localhost"]

# Exclude paths (directories and files)
exclude_path = [
  "site/",                        # MkDocs build output
  "tests/data/",                  # Test data fixtures
  "tests/e2e/output/",            # Test output artifacts
  "tests/e2e/output_subprocess/", # Subprocess test output
]

# Retry settings
max_retries = 2
timeout = 20

# Accept status codes
accept = [200, 204, 206, 301, 302, 307, 308, 429]

# User agent
user_agent = "Mozilla/5.0 (compatible; lychee/link-checker)"
