site_name: Tom's Knowledge Base
site_description: Personal notes, blog, and reference library
site_author: Tom
site_url: https://notes.tom.dev  # Update with your actual domain

# Repository
repo_url: https://github.com/tommcd/notes  # Update with your repo
repo_name: tommcd/notes
edit_uri: edit/main/notes/

# Content source
docs_dir: .  # Use repo root as docs directory

# Output
site_dir: dist/mkdocs

# Theme
theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant        # Fast page loading
    - navigation.tracking       # URL updates on scroll
    - navigation.tabs           # Top-level tabs
    - navigation.sections       # Collapsible sections
    - navigation.expand         # Expand all sections
    - navigation.indexes        # Section index pages
    - navigation.top            # Back to top button
    - search.suggest            # Search suggestions
    - search.highlight          # Highlight search terms
    - search.share              # Share search results
    - toc.follow                # TOC follows scroll
    - content.code.copy         # Copy code button
    - content.action.edit       # Edit page button
  icon:
    repo: fontawesome/brands/github

# Navigation
nav:
  - Home: index.md
  - Notes:
    - notes/index.md
  - Blog:
    - blog/index.md
  - References:
    - references/index.md
  - About: about.md

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'

  # Blog support (requires mkdocs-blog-plugin or mkdocs-blogging-plugin)
  - blog:
      blog_dir: blog
      blog_toc: true
      post_dir: "{blog}/posts"
      post_date_format: medium
      post_url_format: "{date}/{slug}"
      archive: true
      archive_name: Archive
      archive_date_format: yyyy
      archive_url_format: "archive/{date}"
      categories: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
      authors: true
      draft: false
      draft_on_serve: true
      pagination: true
      pagination_per_page: 10

  # Awesome pages for flexible navigation
  - awesome-pages:
      collapse_single_pages: false

  # Roamlinks for [[wikilink]] support
  - roamlinks:
      # Enable wikilinks like [[Page Name]]

  # BibTeX citations (requires mkdocs-bibtex)
  # - bibtex:
  #     bib_file: "data/derived/references.bib"
  #     cite_style: "pandoc"

  # Git revision dates (optional)
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago

# Markdown Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section
      toc_depth: 3

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS/JS
extra_css:
  # - stylesheets/extra.css

extra_javascript:
  # - javascripts/extra.js
  # MathJax for equations
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra metadata
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tommcd
      name: GitHub
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/yourhandle
    #   name: Twitter
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  generator: false  # Hide "Made with Material for MkDocs"

# Copyright
copyright: >
  Copyright &copy; 2025 Tom –
  <a href="#__consent">Cookie settings</a>
